definitions:
  auth.LoginGoogleRequest:
    properties:
      code:
        type: string
    type: object
  auth.LoginGoogleResponse:
    properties:
      data:
        $ref: '#/definitions/auth.LoginGoogleResponseData'
    type: object
  auth.LoginGoogleResponseData:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/users.User'
    type: object
  transactions.CreateIncomeRequest:
    properties:
      amount:
        maximum: 999999
        minimum: 0
        type: number
      description:
        type: string
      name:
        type: string
      reference_date:
        type: string
    required:
    - amount
    - name
    - reference_date
    type: object
  transactions.CreateInstallmentRequest:
    properties:
      description:
        type: string
      name:
        type: string
      reference_date:
        type: string
      total_amount:
        maximum: 999999
        minimum: 0
        type: number
      total_installments:
        maximum: 100
        minimum: 1
        type: integer
    required:
    - name
    - reference_date
    - total_amount
    - total_installments
    type: object
  transactions.CreateInstallmentResponse:
    properties:
      data:
        $ref: '#/definitions/transactions.CreateInstallmentResponseData'
    type: object
  transactions.CreateInstallmentResponseData:
    properties:
      entries:
        items:
          $ref: '#/definitions/transactions.ViewEntry'
        type: array
    type: object
  transactions.TransactionType:
    enum:
    - simple_expense
    - income
    - installment
    type: string
    x-enum-varnames:
    - SimpleExpense
    - Income
    - Installment
  transactions.ViewEntry:
    properties:
      amount:
        type: number
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      installment:
        type: integer
      name:
        type: string
      period:
        type: string
      reference_date:
        type: string
      total_amount:
        type: number
      total_installments:
        type: integer
      transaction_id:
        type: string
      type:
        $ref: '#/definitions/transactions.TransactionType'
      user_id:
        type: string
    type: object
  users.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  utils.HTTPError:
    properties:
      error:
        $ref: '#/definitions/utils.HTTPErrorData'
      status:
        type: integer
    type: object
  utils.HTTPErrorData:
    properties:
      message:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
  title: Money API
paths:
  /auth/login/google:
    post:
      consumes:
      - application/json
      description: Authenticates user with Google OAuth
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginGoogleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in
          schema:
            $ref: '#/definitions/auth.LoginGoogleResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Login with Google
      tags:
      - auth
  /transactions/{transaction_id}:
    delete:
      consumes:
      - application/json
      description: Delete a transaction and all entries related by the ID of the transaction
      parameters:
      - description: transaction ID
        in: path
        name: transaction_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Transaction deleted
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Delete Transaction By ID
      tags:
      - transactions
  /transactions/income:
    post:
      consumes:
      - application/json
      description: Create an income transactions and entry
      parameters:
      - description: Income payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transactions.CreateIncomeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Income transaction created
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create an income
      tags:
      - transactions
  /transactions/installment:
    post:
      consumes:
      - application/json
      description: Create an installment transactions and entries
      parameters:
      - description: Installment payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transactions.CreateInstallmentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Transaction created
          schema:
            $ref: '#/definitions/transactions.CreateInstallmentResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create an installment
      tags:
      - transactions
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
