definitions:
  auth.LoginGoogleRequest:
    properties:
      code:
        type: string
    type: object
  auth.LoginGoogleResponse:
    properties:
      data:
        $ref: '#/definitions/auth.LoginGoogleResponseData'
    type: object
  auth.LoginGoogleResponseData:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/users.User'
    type: object
  categories.Category:
    properties:
      color:
        type: string
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      user_id:
        type: string
    type: object
  categories.CategoryAmountPerPeriod:
    properties:
      color:
        type: string
      id:
        type: string
      name:
        type: string
      period:
        type: string
      total_amount:
        type: number
      user_id:
        type: string
    type: object
  categories.CreateCategoryRequest:
    properties:
      color:
        type: string
      name:
        type: string
    required:
    - color
    - name
    type: object
  categories.CreateCategoryResponse:
    properties:
      data:
        $ref: '#/definitions/categories.CreateCategoryResponseData'
    type: object
  categories.CreateCategoryResponseData:
    properties:
      category:
        $ref: '#/definitions/categories.Category'
    type: object
  categories.ListCategoriesResponse:
    properties:
      data:
        $ref: '#/definitions/categories.ListCategoriesResponseData'
      query:
        $ref: '#/definitions/utils.QueryMeta'
    type: object
  categories.ListCategoriesResponseData:
    properties:
      categories:
        items:
          $ref: '#/definitions/categories.Category'
        type: array
    type: object
  categories.ListCategoryAmountPerPeriodResponse:
    properties:
      data:
        $ref: '#/definitions/categories.ListCategoryAmountPerPeriodResponseData'
      query:
        $ref: '#/definitions/utils.QueryMeta'
    type: object
  categories.ListCategoryAmountPerPeriodResponseData:
    properties:
      categories:
        items:
          $ref: '#/definitions/categories.CategoryAmountPerPeriod'
        type: array
    type: object
  categories.UpdateCategoryRequest:
    properties:
      color:
        type: string
      name:
        type: string
    type: object
  categories.UpdateCategoryResponse:
    properties:
      data:
        $ref: '#/definitions/categories.UpdateCategoryResponseData'
    type: object
  categories.UpdateCategoryResponseData:
    properties:
      category:
        $ref: '#/definitions/categories.Category'
    type: object
  transactions.CreateIncomeRequest:
    properties:
      amount:
        maximum: 999999
        minimum: 0
        type: number
      description:
        type: string
      name:
        type: string
      reference_date:
        type: string
    required:
    - amount
    - name
    - reference_date
    type: object
  transactions.CreateIncomeResponse:
    properties:
      data:
        $ref: '#/definitions/transactions.CreateIncomeResponseData'
    type: object
  transactions.CreateIncomeResponseData:
    properties:
      entry:
        $ref: '#/definitions/transactions.ViewEntry'
    type: object
  transactions.CreateInstallmentRequest:
    properties:
      category_id:
        type: string
      description:
        type: string
      name:
        type: string
      reference_date:
        type: string
      total_amount:
        maximum: 999999
        minimum: 0
        type: number
      total_installments:
        maximum: 100
        minimum: 1
        type: integer
    required:
    - name
    - reference_date
    - total_amount
    - total_installments
    type: object
  transactions.CreateInstallmentResponse:
    properties:
      data:
        $ref: '#/definitions/transactions.CreateInstallmentResponseData'
    type: object
  transactions.CreateInstallmentResponseData:
    properties:
      entries:
        items:
          $ref: '#/definitions/transactions.ViewEntry'
        type: array
    type: object
  transactions.CreateSimpleExpenseRequest:
    properties:
      amount:
        maximum: 999999
        minimum: 0
        type: number
      description:
        type: string
      name:
        type: string
      reference_date:
        type: string
    required:
    - amount
    - name
    - reference_date
    type: object
  transactions.CreateSimpleExpenseResponse:
    properties:
      data:
        $ref: '#/definitions/transactions.CreateSimpleExpenseResponseData'
    type: object
  transactions.CreateSimpleExpenseResponseData:
    properties:
      entry:
        $ref: '#/definitions/transactions.ViewEntry'
    type: object
  transactions.ListEntriesResponse:
    properties:
      data:
        $ref: '#/definitions/transactions.ListEntriesResponseData'
      query:
        $ref: '#/definitions/utils.QueryMeta'
    type: object
  transactions.ListEntriesResponseData:
    properties:
      entries:
        items:
          $ref: '#/definitions/transactions.ViewEntry'
        type: array
    type: object
  transactions.TransactionType:
    enum:
    - simple_expense
    - income
    - installment
    type: string
    x-enum-varnames:
    - SimpleExpense
    - Income
    - Installment
  transactions.ViewEntry:
    properties:
      amount:
        type: number
      category_color:
        type: string
      category_id:
        type: string
      category_name:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      installment:
        type: integer
      name:
        type: string
      period:
        type: string
      reference_date:
        type: string
      total_amount:
        type: number
      total_installments:
        type: integer
      transaction_id:
        type: string
      type:
        $ref: '#/definitions/transactions.TransactionType'
      user_id:
        type: string
    type: object
  users.User:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  utils.HTTPError:
    properties:
      error:
        $ref: '#/definitions/utils.HTTPErrorData'
      status:
        type: integer
    type: object
  utils.HTTPErrorData:
    properties:
      message:
        type: string
      type:
        type: string
    type: object
  utils.QueryMeta:
    properties:
      next_page:
        type: boolean
      page:
        type: integer
      per_page:
        type: integer
      total_items:
        type: integer
      total_pages:
        type: integer
    type: object
info:
  contact: {}
  title: Money API
paths:
  /auth/login/google:
    post:
      consumes:
      - application/json
      description: Authenticates user with Google OAuth
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginGoogleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User logged in
          schema:
            $ref: '#/definitions/auth.LoginGoogleResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: Login with Google
      tags:
      - auth
  /categories:
    get:
      consumes:
      - application/json
      description: List categories
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: per_page
        type: integer
      - description: Sort field
        example: name
        in: query
        name: sort
        type: string
      - default: asc
        description: Sort order (asc/desc)
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      - description: A category name to filter by
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of categories
          schema:
            $ref: '#/definitions/categories.ListCategoriesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: List categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a category
      parameters:
      - description: Category payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/categories.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Category created
          schema:
            $ref: '#/definitions/categories.CreateCategoryResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create a category
      tags:
      - categories
  /categories/{category_id}:
    delete:
      consumes:
      - application/json
      description: Delete a category
      parameters:
      - description: category ID
        in: path
        name: category_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Category deleted
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Delete Category By ID
      tags:
      - categories
    patch:
      consumes:
      - application/json
      description: Update a category
      parameters:
      - description: category ID
        in: path
        name: category_id
        required: true
        type: string
      - description: Category payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/categories.UpdateCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Category updated
          schema:
            $ref: '#/definitions/categories.UpdateCategoryResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Update Category By ID
      tags:
      - categories
  /categories/{period}:
    get:
      consumes:
      - application/json
      description: List categories with amount per period
      parameters:
      - description: period
        in: path
        name: period
        required: true
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: per_page
        type: integer
      - description: Sort field
        example: name
        in: query
        name: sort
        type: string
      - default: asc
        description: Sort order (asc/desc)
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of categories with amount per period
          schema:
            $ref: '#/definitions/categories.ListCategoryAmountPerPeriodResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: List categories with amount per period
      tags:
      - categories
  /transactions/{transaction_id}:
    delete:
      consumes:
      - application/json
      description: Delete a transaction and all entries related by the ID of the transaction
      parameters:
      - description: transaction ID
        in: path
        name: transaction_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Transaction deleted
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Delete Transaction By ID
      tags:
      - transactions
  /transactions/entries/{period}:
    get:
      consumes:
      - application/json
      description: List a detailed view of entries joined with transactions for a
        given period
      parameters:
      - description: period in format YYYYMM
        in: path
        name: period
        required: true
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: per_page
        type: integer
      - description: Sort field
        example: name
        in: query
        name: order_by
        type: string
      - default: asc
        description: Sort order (asc/desc)
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of entries
          schema:
            $ref: '#/definitions/transactions.ListEntriesResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: List entries
      tags:
      - transactions
  /transactions/income:
    post:
      consumes:
      - application/json
      description: Create an income transactions and entry
      parameters:
      - description: Income payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transactions.CreateIncomeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Income transaction created
          schema:
            $ref: '#/definitions/transactions.CreateIncomeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create an income
      tags:
      - transactions
  /transactions/installment:
    post:
      consumes:
      - application/json
      description: Create an installment transactions and entries
      parameters:
      - description: Installment payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transactions.CreateInstallmentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Transaction created
          schema:
            $ref: '#/definitions/transactions.CreateInstallmentResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create an installment
      tags:
      - transactions
  /transactions/simple-expense:
    post:
      consumes:
      - application/json
      description: Create a Simple Expense transaction and entry
      parameters:
      - description: Simple Expense payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/transactions.CreateSimpleExpenseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Simple Expense created
          schema:
            $ref: '#/definitions/transactions.CreateSimpleExpenseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      security:
      - BearerAuth: []
      summary: Create a Simple Expense
      tags:
      - transactions
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
