name: Deploy to GCP

on:
  workflow_dispatch:

jobs:
  migrate-db:
    name: ${{ vars.MIGRATE_APP_DB_JOB_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin/
          migrate -version

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          migrate -path ./migrations -database "$DATABASE_URL" up

  deploy:
    needs: migrate-db
    name: ${{ vars.DEPLOY_JOB_NAME }}
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/site:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: |
          gcloud run deploy site \
            --image $IMAGE_NAME \
            --region us-central1 \
            --memory 128Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 80 \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},JWT_SECRET=${{ secrets.JWT_SECRET }},DATABASE_URL=${{ secrets.DATABASE_URL }},"ORIGINS=${{ vars.ORIGINS }}"
